version: '3'

services:
    db:
        image: postgres
    web:
        build: .
        command: ./run_mcp.sh
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
