Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.hostname = "testserver"

  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 389, host: 389
  config.vm.network "forwarded_port", guest: 636, host: 636

  config.vm.synced_folder "./", "/vagrant",type:'virtualbox'
  config.vm.synced_folder "../", "/srv/mcp"

  config.vm.provision "shell", inline: <<-SHELL
     apt-get install -y vim systemd-sysv
     apt-get install -y samba ldap-utils winbind
     rm /etc/samba/smb.conf
     samba-tool domain provision --use-rfc2307 --realm hackspace.internal --domain hackspace --server-role=dc --dns-backend=SAMBA_INTERNAL
     samba-tool domain passwordsettings set --complexity=off
     samba-tool user setexpiry Administrator --noexpiry
     samba-tool user setpassword administrator --newpassword="Password4LDAP"
     /etc/init.d/samba stop
     killall -9 winbindd # yeah, dont even ask

     cp /vagrant/samba/smb.conf /etc/samba/smb.conf
     openssl req -newkey rsa:2048 -keyout /etc/samba/tls/samba.key -nodes -x509 -days 365 -out /etc/samba/tls/samba.cer -subj "/C=UK/ST=Greater Manchester/L=Manchester/CN=testserver.hackspace.internal"
     chmod 600 /etc/samba/tls/samba.key
     cp /vagrant/samba/ldap.conf /etc/ldap/

     echo "127.0.0.1 testserver.hackspace.internal" | tee -a /etc/hosts

     /etc/init.d/samba start
     sleep 10

     ldapadd -w Password4LDAP -D 'administrator@hackspace.internal' -f /vagrant/ldap/createGroups.ldif -c

     apt-get install -y python3 python-ldap3
     cd /vagrant/ldap/
     python3 import_existing_users.py

     # now we'll set up nginx + flask
     apt-get install -y nginx virtualenv libpython3-dev libffi-dev

     cd /srv/mcp
     virtualenv -p python3 venv

     rm -f /etc/nginx/sites-enabled/default
     cp /vagrant/nginx/mcp /etc/nginx/sites-available/
     ln -s /etc/nginx/sites-available/mcp /etc/nginx/sites-enabled/mcp

     /etc/init.d/nginx restart

     source venv/bin/activate
     pip install -r requirements.txt

     cp /vagrant/systemd/mcp.service /lib/systemd/system/
     systemctl enable mcp
     systemctl start mcp

   SHELL
end
